source 'https://github.com/CocoaPods/Specs.git' # 官方库

project 'Runner.xcodeproj'

platform :ios, '15.0'

inhibit_all_warnings!

# 这里需要添加
workspace 'Runner.xcworkspace'

# APP需要的Swift库

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup


def swift_Third
  
  # 网络请求
  pod 'Moya', '~> 15.0'
  
  # 布局约束
  pod 'SnapKit', '~> 5.7.1'
  
  # 键盘管理
  pod 'IQKeyboardManagerSwift', '~> 6.5.16'
  
  # 图片加载
  pod 'Kingfisher', '~> 7.10.1'
  
  # JSON处理
  pod 'SwiftyJSON', '~> 5.0'
  
  # 本地存储
  pod 'KeychainAccess', '~> 4.2'
  
  pod 'MJRefresh', '~> 3.7.9'

  end





target 'Runner' do

  use_frameworks!

  use_modular_headers!
  swift_Third
  
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
    
end



post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
    flutter_additional_ios_build_settings(target)

  end
end

